<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <VerzionFileContent>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/Verzion.cs'))</VerzionFileContent>
    <Version>$([System.Text.RegularExpressions.Regex]::Match($(VerzionFileContent), `(?&lt;=\= "V?)[0-9\.]+`).Value)</Version>
  </PropertyGroup>
  <Target Name="PrintVersion">
    <Message Text="Version is: $(Version)" Importance="high" />
  </Target>
</Project>
